version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: bundle install
          command: docker-compose run app bundle install
      - run:
          name: setup db
          command: docker-compose run app rails db:create db:migrate
      - run:
          name: "wait for db"
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: seed db
          command: docker-compose run app rails db:seed_fu
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: rubocop
          command: docker-compose run app rubocop
      - run:
          name: rspec
          command: docker-compose run app rspec
      - run:
          name: docker-compose down
          command: docker-compose down
